sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /camera/depth/points
   max_range: 7.0
   frame_subsample: 1
   point_subsample: 1
   test_param: 1.42
   filtered_cloud_topic: filtered_cloud
